#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu May 21 14:59:00 PKT 2026
maven-metadata-luckperms.xml.error=
maven-metadata-luckperms.xml.lastUpdated=1779357540210
maven-metadata-papermc.xml.error=
maven-metadata-papermc.xml.lastUpdated=1779357540210
maven-metadata-triumphteam.xml.lastUpdated=1779357540210
